language: node_js
sudo: required
cache:
  yarn: true
  directories:
    - /node_modules
notifications:
  email: false
node_js:
  - '10'
  - '11'
addons:
  chrome: stable
before_script:
  - yarn
script:
  - yarn build:core
  - yarn build:ui
